# Generated by Django 5.0 on 2023-12-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defeito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_web', models.IntegerField()),
                ('mk', models.IntegerField()),
                ('descricao', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_web', models.IntegerField()),
                ('mk', models.IntegerField()),
                ('descricao', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_web', models.IntegerField()),
                ('mk', models.IntegerField()),
                ('descricao', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk', models.IntegerField()),
                ('url', models.URLField()),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MotivoCancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_web', models.IntegerField()),
                ('mk', models.IntegerField()),
                ('descricao', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='NivelSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_web', models.IntegerField()),
                ('mk', models.IntegerField()),
                ('descricao', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_web', models.IntegerField()),
                ('mk', models.IntegerField()),
                ('descricao', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_web', models.IntegerField()),
                ('mk', models.IntegerField()),
                ('descricao', models.CharField(max_length=128)),
            ],
        ),
    ]
