version: '3.8'

services:
  psql:
    image: postgres:16
    container_name: psql
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  automacao:
    container_name: automacao
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    shm_size: 4g
    tty: true
    depends_on:
      - psql