version: '3.9'

services:
  psql:
    container_name: psql
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    env_file:
      - dotenv_files/.env

  gerenciador:
    container_name: gerenciador
    build:
      context: ./gerenciador
    ports:
      - 8000:8000
    volumes:
      - ./gerenciador:/gerenciador
    env_file:
      - dotenv_files/.env
    depends_on:
      - psql