version: '3.9'

services:
  psql:
    image: postgres:latest
    container_name: psql-noc
    environment:
      POSTGRES_DB: bot_sistema
      POSTGRES_USER: ralds
      POSTGRES_PASSWORD: ralds
    ports:
      - "5432:5432"
    # volumes:
    #   - ./data:/var/lib/postgresql/data


  gerenciador:
    container_name: gerenciador
    build:
      context: ./gerenciador
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - psql