# Generated by Django 4.2.5 on 2023-09-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSLA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Alertas',
            },
        ),
        migrations.CreateModel(
            name='InformacaoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Informacoes_OS',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('cod_os', models.IntegerField(default=0)),
                ('data_envio', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('alerta_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imri.alertasla')),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('login_mk', models.CharField(max_length=200)),
                ('chat_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tecnicos',
            },
        ),
        migrations.CreateModel(
            name='TipoOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('sla', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Tipo_OS',
            },
        ),
        migrations.RemoveField(
            model_name='informacoesos',
            name='id_tipo_os',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.RemoveField(
            model_name='sla_os',
            name='id_tipo_os',
        ),
        migrations.RemoveField(
            model_name='tecnicosmensagem',
            name='chat_id',
        ),
        migrations.DeleteModel(
            name='TempoSLA',
        ),
        migrations.DeleteModel(
            name='InformacoesOS',
        ),
        migrations.DeleteModel(
            name='SLA_OS',
        ),
        migrations.DeleteModel(
            name='Tecnicos',
        ),
        migrations.DeleteModel(
            name='TecnicosMensagem',
        ),
        migrations.DeleteModel(
            name='TiposOS',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='tecnico_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imri.tecnico'),
        ),
        migrations.AddField(
            model_name='informacaoos',
            name='id_tipo_os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imri.tipoos'),
        ),
    ]
