# Generated by Django 5.0 on 2024-01-03 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsGoon',
            fields=[
                ('numero_os', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ordem_servico_externa', models.CharField(blank=True, max_length=11, null=True)),
                ('descricao', models.CharField(max_length=256)),
                ('tipo_servico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StatusInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField()),
                ('status', models.CharField(max_length=8)),
                ('data', models.DateTimeField()),
                ('mobile_agent', models.CharField(max_length=128)),
                ('mobile_phone', models.CharField(max_length=64)),
                ('enviado', models.BooleanField(default=False)),
                ('os_goon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_info', to='goontodesk.osgoon')),
            ],
        ),
    ]
