# Generated by Django 5.0 on 2024-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goontodesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusinfo',
            name='data',
            field=models.CharField(max_length=64),
        ),
    ]
