# Generated by Django 5.0 on 2024-01-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goontodesk', '0002_alter_statusinfo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusinfo',
            name='mobile_agent',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='statusinfo',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
