# Generated by Django 5.0.1 on 2024-01-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goontodesk', '0003_alter_statusinfo_mobile_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osgoon',
            name='tipo_servico',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
