# Generated by Django 4.2.5 on 2023-09-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('automovel', models.CharField(max_length=128)),
                ('placa', models.CharField(max_length=7)),
                ('velocidade', models.IntegerField()),
                ('horario', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
            ],
        ),
    ]
