# Generated by Django 5.0.1 on 2024-03-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('processamento', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadMovimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_thread', models.IntegerField()),
            ],
        ),
    ]
