# Generated by Django 5.0.1 on 2024-01-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statusgoon',
            old_name='id',
            new_name='descricao',
        ),
    ]
