# Generated by Django 5.0 on 2023-12-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk', models.IntegerField()),
                ('grupo_atendimento_os', models.CharField(max_length=128)),
                ('limite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk', models.IntegerField()),
                ('cod_pessoa', models.IntegerField()),
                ('qtd_conexoes', models.IntegerField()),
                ('conexao_associada', models.IntegerField()),
                ('os_cancelamento_ou_recolhimento', models.CharField(max_length=1)),
                ('documento', models.CharField(max_length=18)),
                ('tipo_os', models.CharField(max_length=128)),
                ('grupo_atendimento_os', models.CharField(max_length=128)),
                ('detalhes_os', models.CharField(max_length=512)),
                ('nivel_sla', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=False)),
                ('processamento', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ordens de Serviço',
            },
        ),
        migrations.CreateModel(
            name='ThreadOs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_thread', models.IntegerField()),
            ],
        ),
    ]
