# Generated by Django 5.0.1 on 2024-03-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.CharField(help_text='ex: 0923-000052', max_length=11, primary_key=True, serialize=False)),
                ('data_criacao', models.DateField()),
                ('data_finalizacao', models.DateField(blank=True, null=True)),
                ('assunto', models.CharField(max_length=128)),
                ('nome_categoria', models.CharField(max_length=128)),
                ('total_horas_1_2_atendimento_str', models.CharField(help_text='ex: 0000:04:00', max_length=32)),
                ('total_horas_1_2_atendimento', models.FloatField(editable=False)),
                ('nome_sla_status_atual', models.CharField(blank=True, max_length=128, null=True)),
                ('sla_2_expirado', models.CharField(max_length=128)),
                ('first_call', models.CharField(help_text='ex: N ou S', max_length=1)),
                ('nome_operador', models.CharField(max_length=128)),
                ('nome_status', models.CharField(max_length=128)),
                ('sla_1_expirado', models.CharField(blank=True, max_length=128, null=True)),
                ('total_horas_1_atendimento_str', models.CharField(blank=True, help_text='ex: 0000:04:00', max_length=32, null=True)),
                ('total_horas_1_atendimento', models.FloatField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Chamados',
            },
        ),
        migrations.CreateModel(
            name='Interacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_acao_nome_relatorio', models.CharField(max_length=128)),
                ('fantasia_fornecedor', models.CharField(blank=True, max_length=128, null=True)),
                ('seguencia', models.IntegerField()),
                ('chamado_aprovadores', models.CharField(blank=True, max_length=256, null=True)),
                ('tempo_corrido_interacao_str', models.CharField(blank=True, help_text='ex: 0000:04:00', max_length=32, null=True)),
                ('tempo_corrido_interacao', models.FloatField(blank=True, editable=False, null=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='indicador.chamado')),
            ],
            options={
                'verbose_name_plural': 'Interações',
            },
        ),
    ]
