# Generated by Django 5.0.1 on 2024-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='andamento',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='nome_operador',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='nome_status',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='total_horas_1_2_atendimento_str',
            field=models.CharField(default='00:00:00', help_text='ex: 0000:04:00', max_length=32),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='total_horas_1_atendimento',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='total_horas_1_atendimento_str',
            field=models.CharField(default='00:00:00', help_text='ex: 0000:04:00', max_length=32),
        ),
    ]
