# Generated by Django 5.0.1 on 2024-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='tempo_restante_1',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='tempo_restante_2',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='total_horas_1_2_atendimento',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='total_horas_1_atendimento',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
