# Generated by Django 5.0.1 on 2024-03-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaturamentoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk', models.IntegerField()),
                ('data_faturamento', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
