# Generated by Django 5.0.1 on 2024-03-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturamento',
            name='dia_faturamento',
            field=models.IntegerField(default=2),
        ),
    ]
