# Generated by Django 4.2.5 on 2023-09-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recolhimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk', models.IntegerField()),
                ('contrato', models.IntegerField()),
                ('qtd_conexoes', models.IntegerField()),
                ('conexao_associada', models.IntegerField()),
                ('qtd_atendimentos', models.IntegerField()),
                ('os_cancelamento_ou_recolhimento', models.BooleanField(default=False)),
                ('documento', models.CharField(max_length=18)),
                ('tipo_os', models.CharField(max_length=128)),
                ('planos_de_contas', models.CharField(max_length=128)),
                ('grupo_atendimento_os', models.CharField(max_length=128)),
                ('detalhes_os', models.CharField(max_length=512)),
                ('atraso_max', models.IntegerField()),
                ('loja', models.CharField(max_length=128)),
                ('status_recolhimento', models.BooleanField(default=False)),
            ],
        ),
    ]
