# Generated by Django 5.0.1 on 2024-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTelegram',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='BotTelegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=128)),
                ('funcao', models.IntegerField(choices=[(1, 'Colaborador'), (2, 'Analista Sistema'), (3, 'Analista OST'), (4, 'Técnico')], default=1)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
