# Generated by Django 5.0 on 2024-01-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erroros',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
