# Generated by Django 4.2.5 on 2023-09-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
