# Generated by Django 4.2.5 on 2023-09-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0002_ativado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ativado',
        ),
    ]
