# Generated by Django 5.0 on 2024-01-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ost', '0002_erroros_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoos',
            name='sla',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoos',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='SlaOs',
        ),
    ]
