# Generated by Django 5.0 on 2024-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertelegram',
            name='funcao',
            field=models.IntegerField(choices=[(1, 'Técnico'), (2, 'Outros')], default=2),
        ),
    ]
