# Generated by Django 4.2.6 on 2023-11-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk', models.IntegerField()),
                ('contrato', models.IntegerField()),
                ('cod_pessoa', models.IntegerField()),
                ('conexao', models.IntegerField()),
                ('os_cancelamento_30d', models.CharField(blank=True, max_length=128, null=True)),
                ('documento_codigo', models.CharField(max_length=128)),
                ('tipo_os', models.CharField(max_length=128)),
                ('planos_de_contas', models.CharField(max_length=128)),
                ('relato_do_problema', models.TextField()),
                ('detalhes_cancelamento', models.TextField()),
                ('grupo_atendimento_os', models.CharField(max_length=128)),
                ('incidencia_de_multa', models.CharField(max_length=128)),
                ('valor_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vcto_multa_contratual', models.CharField(max_length=128)),
                ('data_a_cancelar', models.CharField(max_length=128)),
                ('loja', models.CharField(max_length=128)),
                ('onu_serial', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
