# Generated by Django 4.2.6 on 2023-11-21 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk', models.IntegerField()),
                ('contrato', models.IntegerField()),
                ('cod_pessoa', models.IntegerField()),
                ('conexao', models.IntegerField()),
                ('os_cancelamento_30d', models.CharField(max_length=128)),
                ('documento_codigo', models.CharField(max_length=128)),
                ('tipo_os', models.CharField(max_length=128)),
                ('planos_de_contas', models.CharField(max_length=128)),
                ('relato_do_problema', models.CharField(max_length=512)),
                ('detalhes_cancelamento', models.CharField(max_length=512)),
                ('grupo_atendimento_os', models.CharField(max_length=128)),
                ('incidencia_de_multa', models.BooleanField(default=False)),
                ('valor_multa', models.FloatField()),
                ('data_vcto_multa_contratual', models.DateField()),
                ('data_a_cancelar', models.DateField()),
                ('loja', models.CharField(max_length=128)),
                ('onu_serial', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=False)),
                ('last_edited_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
