# Generated by Django 5.0 on 2023-12-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancelamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('mk', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_thread', models.IntegerField()),
            ],
        ),
    ]
