# Generated by Django 4.2.7 on 2023-12-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancelamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelamento',
            name='motivo_cancelamento',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cancelamento',
            name='profile',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
