# Generated by Django 5.0 on 2023-12-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancelamento', '0002_thread'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thread',
            new_name='ThreadCancelamento',
        ),
    ]
