# Generated by Django 5.0 on 2023-12-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancelamento', '0003_rename_thread_threadcancelamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threadcancelamento',
            name='mk',
        ),
        migrations.AddField(
            model_name='threadcancelamento',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
